### ISSUE TITLE
Update "We found these matches" page

### ISSUE THREAD

**Issue by chompasina** [codefordenver/Circular#200] opened 2017-11-04 16:51 UTC
![Screen Shot 2017-11-20 at 5.32.26 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/577c1be0dd37d913008c8147/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f36b7191a37df111294f5d595ecc3c4a4356bcbbd671f3e57862804e0eea82690b20c03910ffeb8017b600be208b4786e7b48b45d2f42f67b6d5db1063474f4dcbed5727a19041c95df74ae34f51a7153360ee702431.png)

**Comment by wdoug** [comment] 2018-02-16 01:36
Is this done?

**Comment by wdoug** [comment] 2018-02-16 01:53
Closing as a duplicate of #261

**Closed** 2018-08-09 20:38 UTC
Labels: Style, duplicate, join-campaign epic
